### PR TITLE
Image Optimization (without loss)

### PR DESCRIPTION
**Pull request by shikhir-arora**
See d0352d5

https://github.com/dabutvin/ImgBot

### CODE REVIEW

**Review by siku2 — CHANGES_REQUESTED** [review]
Could you ignore the files in the `_design` folder?

**Comment by shikhir-arora** [comment]
Hm, not sure. It's a bot that does it automatically.

**Comment by siku2** [comment]
No config at all?

**Comment by shikhir-arora** [comment]
You can install it and run it locally, but I just used the GitHub integration of the app. You give it access to the repo, and it scans the images and opens a PR with the optimizations. However, it is a lossless compression algorithm, so there should be no difference (like `FLAC` for audio vs. `WAV`)

**Comment by siku2** [comment]
Oh well, don't mind me then

**Comment by dabutvin** [comment]
Hi there! Thanks for trying out ImgBot.

Just wanted to let you know that there is `.imgbotconfig`
https://imgbot.net/docs#configuration

and specifically you can ignore files https://imgbot.net/docs#ignoring-files

If you are having any problems or would like to see more configuration please feel free to open an issue in https://github.com/dabutvin/ImgBot

**Comment by shikhir-arora** [comment]
Hey, thanks for the clarification and post. My fault there.. Will keep in mind for next time.

**Pull request merged**
